name: Auto Comment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Comment on new issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for opening this issue! Our team will review it soon. 🚀'
          })
    
    - name: Comment on new PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🎉 Thanks for the pull request! Our automated checks are running. ✨'
          })
    
    - name: Log event details
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Action: ${{ github.event.action }}"
        echo "Actor: ${{ github.actor }}"
        if [ "${{ github.event_name }}" = "issues" ]; then
          echo "Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
        fi
