name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Check code formatting with Black
      run: |
        echo "🎨 Checking code formatting..."
        black --check --diff *.py || echo "⚠️ Code formatting issues found"
    
    - name: Check imports with isort
      run: |
        echo "📦 Checking import sorting..."
        isort --check-only --diff *.py || echo "⚠️ Import sorting issues found"
    
    - name: Lint with flake8
      run: |
        echo "🔍 Running flake8 linting..."
        flake8 *.py --count --max-line-length=88 --show-source --statistics || echo "⚠️ Linting issues found"
    
    - name: Show Python file count
      run: |
        echo "📄 Python files in repository:"
        find . -name "*.py" | wc -l
        ls -la *.py
